import time

import driver
from selenium import webdriver
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.select import Select
from webdriver_manager.chrome import ChromeDriverManager

class Test_action:
    def test_action(self):
        driver = webdriver.Chrome(service=Service(ChromeDriverManager().install()))
        driver.maximize_window()
        # navigate to url
        driver.get("https://demowebshop.tricentis.com/login")
        time.sleep(4)
        #register
        register = driver.find_element(By.XPATH,"//a[@class='ico-register']")
        register.click()
        time.sleep(2)
        #Details
        gender = driver.find_element(By.XPATH,"//input[@id='gender-female']")
        gender.click()
        time.sleep(2)
        first_name = driver.find_element(By.XPATH,"//input[@id='FirstName']")
        first_name.send_keys("sushi")
        time.sleep(2)
        last_name = driver.find_element(By.XPATH,"//input[@id='LastName']")
        last_name.send_keys("rekha")
        time.sleep(2)
        email = driver.find_element(By.XPATH, "//input[@id='Email']")
        email.send_keys("sushi@gmail.com")
        time.sleep(2)
        password = driver.find_element(By.XPATH, "//input[@id='Password']")
        password.send_keys("123456")
        time.sleep(2)
        confirmps = driver.find_element(By.XPATH, "//input[@id='ConfirmPassword']")
        confirmps.send_keys("123456")
        time.sleep(2)
        rs = driver.find_element(By.XPATH,"//input[@id='register-button']")
        rs.click()
        time.sleep(2)
        books = driver.find_element(By.XPATH,"//li[@class='inactive']//a[normalize-space()='Books']")
        books.click()
        time.sleep(2)
        addtocart = driver.find_element(By.XPATH,"//div[@class='master-wrapper-content']//div[1]//div[1]//div[2]//div[3]//div[2]//input[1]")
        addtocart.click()
        time.sleep(2)
        cart = driver.find_element(By.XPATH,"//span[normalize-space()='Shopping cart']")
        cart.click()
        time.sleep(2)
        terms_condition = driver.find_element(By.XPATH,"//input[@id='termsofservice']")
        terms_condition.click()
        time.sleep(2)
        checkout = driver.find_element(By.XPATH,"//button[@id='checkout']")
        checkout.click()
        time.sleep(2)
        checkoutguest = driver.find_element(By.XPATH,"//input[@value='Checkout as Guest']")
        checkoutguest.click()
        time.sleep(2)
        firstname = driver.find_element(By.XPATH,"//input[@id='BillingNewAddress_FirstName']")
        firstname.send_keys("P")
        time.sleep(2)
        lastname = driver.find_element(By.XPATH,"//input[@id='BillingNewAddress_LastName']")
        lastname.send_keys("R")
        time.sleep(2)
        Email = driver.find_element(By.XPATH,"//input[@id='BillingNewAddress_Email']")
        Email.send_keys("sushi123@gmail.com")
        time.sleep(2)
        country = Select(driver.find_element(By.XPATH,"//select[@id='BillingNewAddress_CountryId']"))
        country.select_by_visible_text("India")
        time.sleep(2)
        city = driver.find_element(By.XPATH,"//input[@id='BillingNewAddress_City']")
        city.send_keys("AP")
        time.sleep(2)
        address = driver.find_element(By.XPATH,"//input[@id='BillingNewAddress_Address1']")
        address.send_keys("k")
        time.sleep(2)
        postalcode = driver.find_element(By.XPATH,"//input[@id='BillingNewAddress_ZipPostalCode']")
        postalcode.send_keys("3456")
        time.sleep(2)
        phone_number = driver.find_element(By.XPATH,"//input[@id='BillingNewAddress_PhoneNumber']")
        phone_number.send_keys("1234456777")
        time.sleep(2)
        c = driver.find_element(By.XPATH,"//input[@onclick='Billing.save()']")
        c.click()
        time.sleep(2)
        shiping_address = Select(driver.find_element(By.XPATH,"//select[@id='shipping-address-select']"))
        shiping_address.select_by_index(0)
        time.sleep(2)
        c1 = driver.find_element(By.XPATH, "//input[@onclick='Shipping.save()']")
        c1.click()
        time.sleep(2)
        shipping_method= driver.find_element(By.XPATH, "//input[@id='shippingoption_0']")
        shipping_method.click()
        time.sleep(2)
        c2 = driver.find_element(By.XPATH, "//input[@class='button-1 shipping-method-next-step-button']")
        c2.click()
        time.sleep(2)
        payment = driver.find_element(By.XPATH, "//input[@id='paymentmethod_0']")
        payment.click()
        driver.execute_script("arguments[0].scrollIntoView();", payment)
        time.sleep(2)
        c3 = driver.find_element(By.XPATH, "//input[@class='button-1 payment-method-next-step-button']")
        c3.click()
        time.sleep(2)
        c4= driver.find_element(By.XPATH, "//input[@class='button-1 payment-info-next-step-button']")
        c4.click()
        time.sleep(2)
        confirm = driver.find_element(By.XPATH,"//input[@value='Confirm']")
        driver.execute_script("arguments[0].scrollIntoView();", confirm)
        confirm.click()
        time.sleep(2)
        driver.close()